jumps: 86400
start_date: "2018-09-17"
end_date: "2026-01-11"
root: "./data"
date_format: "%Y-%m-%d"
data_path: "./data/one_day_pred.csv"
train_interval: ["2018-09-17", "2023-11-01"]
val_interval: ["2023-11-01", "2024-12-05"]
test_interval: ["2024-12-05", "2026-01-11"]
additional_features: []
